/*
* Generated file
*
* Generated from: yang module name: aaa-authz-service-impl yang module local name: aaa-authz-service
* Generated by: org.opendaylight.controller.config.yangjmxgenerator.plugin.JMXGenerator
* Generated at: Wed May 04 16:37:34 CEST 2016
*
* Do not modify this file unless it is present under src/main directory
*/
package org.opendaylight.controller.config.yang.config.aaa_authz.srv;
public class Policies {
    private org.opendaylight.controller.config.api.DependencyResolver dependencyResolver;

    private org.opendaylight.yang.gen.v1.urn.aaa.yang.authz.ds.rev140722.ServiceType service;

    private org.opendaylight.yang.gen.v1.urn.aaa.yang.authz.ds.rev140722.ResourceType resource;

    private java.lang.String action;

    private org.opendaylight.yang.gen.v1.urn.aaa.yang.authz.ds.rev140722.RoleType role;

    public Policies() {
        super();
    }

    public void injectDependencyResolver(org.opendaylight.controller.config.api.DependencyResolver dependencyResolver) {
        this.dependencyResolver = dependencyResolver;
    }

    public org.opendaylight.yang.gen.v1.urn.aaa.yang.authz.ds.rev140722.ServiceType getService() {
        return service;
    }

    public void setService(org.opendaylight.yang.gen.v1.urn.aaa.yang.authz.ds.rev140722.ServiceType service) {
        this.service = service;
    }

    public org.opendaylight.yang.gen.v1.urn.aaa.yang.authz.ds.rev140722.ResourceType getResource() {
        return resource;
    }

    public void setResource(org.opendaylight.yang.gen.v1.urn.aaa.yang.authz.ds.rev140722.ResourceType resource) {
        this.resource = resource;
    }

    public java.lang.String getAction() {
        return action;
    }

    public void setAction(java.lang.String action) {
        this.action = action;
    }

    public org.opendaylight.yang.gen.v1.urn.aaa.yang.authz.ds.rev140722.RoleType getRole() {
        return role;
    }

    public void setRole(org.opendaylight.yang.gen.v1.urn.aaa.yang.authz.ds.rev140722.RoleType role) {
        this.role = role;
    }

    @Override
    public int hashCode() {
        return java.util.Objects.hash(service, resource, action, role);

    }

    @Override
    public boolean equals(Object o) {
    if (this == o) { return true; }
    if (o == null || getClass() != o.getClass()) { return false; }
        final Policies that = (Policies) o;
        if(java.util.Objects.equals(service, that.service) == false) {
            return false;
        }

        if(java.util.Objects.equals(resource, that.resource) == false) {
            return false;
        }

        if(java.util.Objects.equals(action, that.action) == false) {
            return false;
        }

        if(java.util.Objects.equals(role, that.role) == false) {
            return false;
        }

        return true;

    }

}
